//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAESAR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAESAR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECRYPT.
        /// </summary>
        internal static string DecryptProperty {
            get {
                return ResourceManager.GetString("DecryptProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCRYPT.
        /// </summary>
        internal static string EncryptProperty {
            get {
                return ResourceManager.GetString("EncryptProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is your account code:
        ///
        ///.
        /// </summary>
        internal static string MessageAccountCode {
            get {
                return ResourceManager.GetString("MessageAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAESAR.
        /// </summary>
        internal static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to process..
        /// </summary>
        internal static string MessageNoProcess {
            get {
                return ResourceManager.GetString("MessageNoProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected anything to remove..
        /// </summary>
        internal static string MessageNoRemove {
            get {
                return ResourceManager.GetString("MessageNoRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect PIN..
        /// </summary>
        internal static string MessageWrongPIN {
            get {
                return ResourceManager.GetString("MessageWrongPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to process the files in this folder?.
        /// </summary>
        internal static string ProcessFolderPrompt {
            get {
                return ResourceManager.GetString("ProcessFolderPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want a new key? This will render all currently encrypted files indecipherable..
        /// </summary>
        internal static string PromptNewKey {
            get {
                return ResourceManager.GetString("PromptNewKey", resourceCulture);
            }
        }
    }
}
